/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "no longer usable",
  "description": "...",
  "tags": ['danger'],
  "credits": [
    {
      "name": "Unknown",
      "link": "https://scratch.mit.edu"
    }
  ],
  "enabledByDefault": false,
  "settings": []
};
export default manifest;
