/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "[no longer usable]",
  "description": "...",
  "tags": ['dangerous'],
  "credits": [
    {
      "name": "Unknown",
      "link": "https://scratch.mit.edu"
    }
  ],
  "enabledByDefault": false,
  "disabled": true,
  "settings": [
  ]
};
export default manifest;
